### ISSUE TITLE
error on importing the library

### ISSUE THREAD

**Issue by twalen** [Gawaboumga/iso-20275-python#12]
The version installed from pip does not contain some CSV files and due to that the import of the library fails:

`pip install iso-20275`

```
>>> import iso20275
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.7/site-packages/iso20275/__init__.py", line 198, in <module>
    class Elf(object, metaclass=MetaElf):
  File ".../lib/python3.7/site-packages/iso20275/__init__.py", line 185, in __new__
    elfclass._codes = read_entries(get_csv_paths(newest=True, cleaned=True, additional=True)[0])
  File ".../lib/python3.7/site-packages/iso20275/__init__.py", line 174, in get_csv_paths
    results = (results[0],) if cleaned else results[:3]
IndexError: list index out of range
```

This is due to missing "*with additional*.csv" files in https://files.pythonhosted.org/packages/52/44/b484a5a2827035c11ab72ecf711c98c761d12b40fba89d3ae8f7cbb45dac/iso-20275-0.0.11.tar.gz:
```
$ tar tvzf iso-20275-0.0.11.tar.gz 
drwxrwxrwx  0 0      0           0 Nov 25 22:42 iso-20275-0.0.11/
-rw-rw-rw-  0 0      0       17127 Nov 25 22:42 iso-20275-0.0.11/PKG-INFO
-rw-rw-rw-  0 0      0       13870 Nov 25 22:38 iso-20275-0.0.11/README.rst
drwxrwxrwx  0 0      0           0 Nov 25 22:42 iso-20275-0.0.11/iso20275/
-rw-rw-rw-  0 0      0      250023 Jul 19  2019 iso-20275-0.0.11/iso20275/Cleaned - ISO-20275 - 2017-11-30.csv
-rw-rw-rw-  0 0      0      411598 Jun 19  2020 iso-20275-0.0.11/iso20275/Cleaned - ISO-20275 - 2019-11-06.csv
-rw-rw-rw-  0 0      0      253216 May 30  2019 iso-20275-0.0.11/iso20275/ISO-20275 - 2017-11-30.csv
-rw-rw-rw-  0 0      0      411652 Apr 28  2020 iso-20275-0.0.11/iso20275/ISO-20275 - 2019-11-06.csv
-rw-rw-rw-  0 0      0        6113 Nov 25 22:12 iso-20275-0.0.11/iso20275/__init__.py
-rw-rw-rw-  0 0      0        4209 Nov 25 22:39 iso-20275-0.0.11/iso20275/merge_additional_legal_forms.py
-rw-rw-rw-  0 0      0         817 Nov 23 21:36 iso-20275-0.0.11/iso20275/trim.py
drwxrwxrwx  0 0      0           0 Nov 25 22:42 iso-20275-0.0.11/iso_20275.egg-info/
-rw-rw-rw-  0 0      0       17127 Nov 25 22:42 iso-20275-0.0.11/iso_20275.egg-info/PKG-INFO
-rw-rw-rw-  0 0      0         477 Nov 25 22:42 iso-20275-0.0.11/iso_20275.egg-info/SOURCES.txt
-rw-rw-rw-  0 0      0           1 Nov 25 22:42 iso-20275-0.0.11/iso_20275.egg-info/dependency_links.txt
-rw-rw-rw-  0 0      0          11 Nov 25 22:42 iso-20275-0.0.11/iso_20275.egg-info/requires.txt
-rw-rw-rw-  0 0      0          15 Nov 25 22:42 iso-20275-0.0.11/iso_20275.egg-info/top_level.txt
-rw-rw-rw-  0 0      0          74 Nov 25 22:42 iso-20275-0.0.11/setup.cfg
-rw-rw-rw-  0 0      0        1930 May  3  2020 iso-20275-0.0.11/setup.py
drwxrwxrwx  0 0      0           0 Nov 25 22:42 iso-20275-0.0.11/tests/
-rw-rw-rw-  0 0      0          30 May 30  2019 iso-20275-0.0.11/tests/__init__.py
-rw-rw-rw-  0 0      0        3330 Jun 27  2020 iso-20275-0.0.11/tests/test_iso20275.py
```

I'm not sure what is expected behavior, but probably line:
```
        elfclass._codes = read_entries(get_csv_paths(newest=True, cleaned=True, additional=True)[0])
```

should be changed to:
```
        elfclass._codes = read_entries(get_csv_paths(newest=True, cleaned=True, additional=False)[0])
```

**Comment by Gawaboumga** [comment]
Sorry for the late answer, I'm in the middle of moving. I'm not entirely sure to understand why this error occurs, I applied your change and push the new version.
Thank you for being my only user =)
